import type { Metadata } from "next";
import Link from "next/link";
import { PrivatePageShell } from "@/components/private/private-page-shell";

export const metadata: Metadata = { title: "BEYOND THE COMMENTS", description: "Unlisted youth exchange development concept.", robots: { index: false, follow: false, noarchive: true, nosnippet: true, noimageindex: true } };

function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noopener noreferrer" className="font-medium text-electric underline decoration-electric/30 underline-offset-4 hover:decoration-electric">{children}</a>; }
function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="border-t border-ink/10 py-10 sm:py-12"><div className="grid gap-6 lg:grid-cols-[11rem_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-copper">{number}</p><h2 className="mt-3 font-serif text-3xl font-medium tracking-[-0.03em] text-ink">{title}</h2></div><div className="max-w-3xl space-y-5 text-base leading-8 text-graphite/76">{children}</div></div></section>; }

export default function Page() {
  return <PrivatePageShell><main className="bg-paper"><section className="border-b border-white/10 bg-[#10131a] text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20"><Link href="/private/ideas/youth-exchange" className="text-xs font-semibold uppercase tracking-[0.16em] text-white/52 transition hover:text-white">← Youth Exchange Ideas</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.2em] text-[#d9a6af]">Youth Exchange Concept 04</p><h1 className="mt-4 max-w-5xl font-serif text-5xl font-medium leading-[0.98] tracking-[-0.045em] text-balance sm:text-7xl">BEYOND THE COMMENTS</h1><h2 className="mt-6 max-w-4xl text-xl font-medium leading-8 text-white/72 sm:text-2xl">Young Creators Turning Online Hate into Real-World Dialogue</h2></div></section><div className="mx-auto max-w-7xl px-5 sm:px-8">
<Section number="1" title="Project concept"><p>BEYOND THE COMMENTS is a seven-day Erasmus+ Youth Exchange bringing together young digital creators, niche influencers and media students who already communicate with youth audiences through social media.</p><p>Participants will examine real cases of cyberbullying, hate speech and destructive online conflict. They will develop and test new content formats, moderation approaches and game-based mechanics that encourage constructive interaction and transform digital engagement into meaningful face-to-face dialogue.</p></Section>
<Section number="2" title="Problem and evidence"><p>Young people spend 4.5 hours online on school days and more than six hours during weekends. A 2026 EU survey found that:</p><ul className="list-disc space-y-2 pl-5"><li>25% of adolescents encountered problematic online content, including hate speech;</li><li>almost one in three felt stressed, sad or socially excluded because of social media;</li><li>45% regularly compared themselves with others online;</li><li>nine out of ten reported at least one negative symptom linked to screen use.</li></ul><p><ExternalLink href="https://commission.europa.eu/news-and-media/news/child-safety-online-eu-survey-confirms-link-between-screen-time-and-wellbeing-2026-06-16_en">European Commission, 2026</ExternalLink></p><p>Digital creators shape language, attitudes and group behaviour. However, many lack practical tools for preventing bullying, moderating polarised discussions and responding when online conflict begins affecting people offline.</p></Section>
<Section number="3" title="Target group"><p>The project will involve 36 participants aged 18–30 from partners countries.</p><p>Every participant will manage an active social-media account, channel or online community reaching a youth audience. The group will include established niche creators, emerging creators with strong audience engagement and students working in media, communication or marketing.</p><p>Selection will prioritise audience relevance, engagement quality, motivation and community trust rather than follower count alone. Participants with fewer opportunities and creators representing minority, migrant or underserved communities will receive priority.</p></Section>
<Section number="4" title="Objectives and EU alignment"><p>The project will:</p><ol className="list-decimal space-y-2 pl-5"><li>strengthen the ability of 36 young creators to recognise and respond to cyberbullying, hate speech and escalating online conflict;</li><li>develop practical skills in responsible content creation, community moderation and bystander intervention;</li><li>test game-based digital mechanics that encourage empathy, reflection and constructive disagreement;</li><li>connect online communication with facilitated face-to-face dialogue;</li><li>activate participants’ existing audiences through concrete anti-hate interventions.</li></ol><p>The project directly supports Erasmus+ priorities on digital transformation, inclusion and diversity, participation in democratic life and common European values.</p><p>It also aligns with the EU Action Plan against Cyberbullying, the Digital Services Act and the revised Code of Conduct+ on Countering Illegal Hate Speech Online. <ExternalLink href="https://commission.europa.eu/strategy-and-policy/policies/justice-and-fundamental-rights/combatting-discrimination/racism-and-xenophobia/eu-code-conduct-countering-illegal-hate-speech-online_en">EU Code of Conduct+</ExternalLink></p></Section>
<Section number="5" title="Proposed consortium and expert network"><p>The consortium will include:</p><ul className="list-disc space-y-2 pl-5"><li><ExternalLink href="https://youth-line.org/">Youth Line Netherlands</ExternalLink>;</li><li><ExternalLink href="https://jubuk.wordpress.com/">JuBuK, Germany</ExternalLink>;</li><li><ExternalLink href="https://youth-line.org/">Youth Line Portugal</ExternalLink>;</li><li><ExternalLink href="https://youth-line.org/">Youth Line Latvia</ExternalLink>;</li><li>a Lithuanian youth organisation;</li><li><ExternalLink href="https://www.hillel.org/israel/">Hillel Israel</ExternalLink>.</li></ul><p>The partnership will involve creators working with different youth communities and organisations experienced in inclusion, intercultural dialogue, media literacy and non-formal education.</p><p>Safer Internet Centres, anti-bullying organisations, psychologists, youth workers, platform specialists and trust-and-safety experts will contribute practical knowledge through case clinics and facilitated discussions.</p></Section>
<Section number="6" title="Activity flow"><p>Before the exchange, participants will collect anonymised examples of cyberbullying, hate speech, polarisation and successful community interventions from their own digital environments.</p><p>The seven-day programme will include:</p><ul className="list-disc space-y-2 pl-5"><li>creator introductions and audience mapping;</li><li>analysis of real online-conflict cases;</li><li>identification of hate escalation patterns;</li><li>comment-section and moderation simulations;</li><li>role-play from creator, target, bystander and platform perspectives;</li><li>intercultural dialogue and bias awareness;</li><li>game-based intervention design;</li><li>ethical testing with an invited local youth audience;</li><li>online-to-offline dialogue experiments;</li><li>development of individual anti-hate interventions.</li></ul><p>The programme will use peer learning. Participants will contribute their own experience, facilitate sessions and evaluate each other’s approaches. Experts will support specific case clinics rather than deliver the programme as lectures.</p></Section>
<Section number="7" title="Experimental methods"><p>International teams will design and test new mechanisms for healthier digital interaction, including:</p><ul className="list-disc space-y-2 pl-5"><li>interactive story choices showing the consequences of online behaviour;</li><li>comment prompts that interrupt impulsive reactions;</li><li>digital empathy challenges;</li><li>bystander-response games;</li><li>collaborative content formats between creators with different audiences;</li><li>mechanisms that invite followers into moderated offline dialogue;</li><li>alternative ways to respond to hostile comments without amplifying them.</li></ul><p>Testing will examine whether each mechanism encourages reflection, participation and constructive communication. Participants will improve their interventions using feedback from the group and invited local young people.</p></Section>
<Section number="8" title="European added value"><p>Online hate crosses borders, but its language, targets and cultural context differ between countries. Working with creators from six countries allows participants to compare how antisemitism, racism, xenophobia, misogyny, religious intolerance and other forms of bullying appear across different digital communities.</p><p>The project connects audiences that rarely interact and gives niche creators access to international peer support. Participants will learn how cultural assumptions affect humour, language, moderation and perceptions of harm.</p><p>The exchange will create a European network of young creators able to collaborate when online hate spreads across platforms or national contexts.</p></Section>
<Section number="9" title="Format and location"><p>Proposed action: KA152 Youth Exchange.</p><p>The exchange will involve 36 young people from six countries, one group leader from each country and two facilitators. It will include seven activity days, excluding travel days.</p><p>The exchange will take place in one participating country and combine workshop-based learning with local community interaction. The host organisation will invite 30 local young people to test selected game mechanics and participate in a facilitated online-to-offline dialogue.</p><p>The project will remain non-commercial. Activities will not promote brands, paid campaigns, creator monetisation or commercial influencer services.</p></Section>
<Section number="10" title="Participant action and sustainability"><p>Within 30 days after the exchange, every participant will:</p><ul className="list-disc space-y-2 pl-5"><li>publish one original anti-hate intervention through their social-media channel;</li><li>conduct one moderated online discussion with their audience;</li><li>organise or co-host one face-to-face dialogue involving at least 10 young people.</li></ul><p>The project will therefore produce 36 public interventions, 36 moderated digital discussions and 36 local dialogue activities reaching at least 360 young people offline, in addition to the participants’ online audiences.</p><p>The partners will compile the tested methods into the <strong>Beyond the Comments Creator Playbook</strong>, containing practical formats, moderation scripts, games and response mechanisms that other youth organisations and creators can reuse.</p></Section>
</div></main></PrivatePageShell>;
}
