import type { Metadata } from "next";
import Link from "next/link";
import { PrivatePageShell } from "@/components/private/private-page-shell";

export const metadata: Metadata = { title: "MOSAIC: ROOTS IN MOTION", description: "Unlisted youth exchange development concept.", robots: { index: false, follow: false, noarchive: true, nosnippet: true, noimageindex: true } };

function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noopener noreferrer" className="font-medium text-electric underline decoration-electric/30 underline-offset-4 hover:decoration-electric">{children}</a>; }
function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="border-t border-ink/10 py-10 sm:py-12"><div className="grid gap-6 lg:grid-cols-[11rem_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-copper">{number}</p><h2 className="mt-3 font-serif text-3xl font-medium tracking-[-0.03em] text-ink">{title}</h2></div><div className="max-w-3xl space-y-5 text-base leading-8 text-graphite/76">{children}</div></div></section>; }

export default function Page() {
  return <PrivatePageShell><main className="bg-paper"><section className="border-b border-white/10 bg-[#10131a] text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20"><Link href="/private/ideas/youth-exchange" className="text-xs font-semibold uppercase tracking-[0.16em] text-white/52 transition hover:text-white">← Youth Exchange Ideas</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.2em] text-[#d9a6af]">Youth Exchange Concept 03</p><h1 className="mt-4 max-w-5xl font-serif text-5xl font-medium leading-[0.98] tracking-[-0.045em] text-balance sm:text-7xl">MOSAIC: ROOTS IN MOTION</h1><h2 className="mt-6 max-w-4xl text-xl font-medium leading-8 text-white/72 sm:text-2xl">From Migration Stories to Local Action</h2></div></section><div className="mx-auto max-w-7xl px-5 sm:px-8">
<Section number="1" title="Project concept"><p>MOSAIC: ROOTS IN MOTION is a seven-day Erasmus+ Youth Exchange bringing together young migrants, refugees, international students and first-generation residents from six countries.</p><p>Participants will explore how migration, family history, religion, ethnicity and personal experience shape identity and belonging. Through storytelling, intercultural dialogue and non-formal learning, they will move from exchanging experiences to organising concrete local actions.</p></Section>
<Section number="2" title="Problem and evidence"><p>On 1 January 2025, 46.7 million EU residents were born outside the EU and another 18 million were born in a different EU country. Migration is a central part of European society, but inclusion remains unequal. <ExternalLink href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=EU_population_diversity_by_citizenship_and_country_of_birth">Eurostat</ExternalLink></p><p>In 2023, young non-EU citizens were:</p><ul className="list-disc space-y-2 pl-5"><li>three times more likely to leave education early;</li><li>twice as likely to be outside employment, education or training;</li><li>twice as likely to face poverty or social exclusion: 47.2%, compared with 21.8% among young nationals.</li></ul><p><ExternalLink href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_-_socioeconomic_situation_of_young_people">Eurostat</ExternalLink></p><p>These inequalities are reinforced by discrimination, limited contact between communities and public debates that discuss migrants without involving them.</p></Section>
<Section number="3" title="Target group"><p>The project will involve 36 participants aged 18–30:</p><ul className="list-disc space-y-2 pl-5"><li>6 from the Netherlands;</li><li>6 from Germany;</li><li>6 from Portugal;</li><li>6 from Latvia;</li><li>6 from Lithuania;</li><li>6 from Israel.</li></ul><p>Participants will have migrant, refugee, international-student or first-generation family backgrounds. Recruitment will ensure diversity of religion, ethnicity, gender, migration route, economic situation and political perspective.</p><p>No participant will be required to disclose their legal status, trauma or personal history.</p></Section>
<Section number="4" title="Objectives and EU alignment"><p>The project will:</p><ol className="list-decimal space-y-2 pl-5"><li>strengthen participants’ sense of belonging and confidence in expressing complex identities;</li><li>develop intercultural dialogue, active listening, conflict-navigation and storytelling skills;</li><li>challenge stereotypes through direct interaction between people with different migration and family histories;</li><li>support participants in creating one concrete intercultural action in every partner country.</li></ol><p>The project supports Erasmus+ priorities on inclusion and diversity, participation in democratic life life and common European values. It Youth Goals #3 “Inclusive Societies”, #4 “InformationInformation and Constructive Dialogue” and #9 “Space and Participation for All”.</p><p>It also aligns with the EU Action Plan on Integration and Inclusion 2022021– Years, which priorit promotes encounters between migrants, people with migrant backgrounds and host communities. <ExternalLink href="https://home-affairs.ec.europa.eu/policies/migration-and-asylum/migrant-integration/migrant-integration-hub/progress-tracker-action-plan-integration-and-inclusion-2021-202">EU Action Plan</ExternalLink> Years_en</p></Section>
<Section number="5" title="Proposed consortium"><p>The consortium will combine organisations with access to migrant youth and experience in international non-formal education:</p><ul className="list-disc space-y-2 pl-5"><li><ExternalLink href="https://youth-line.org/">Youth Line Netherlands</ExternalLink>;</li><li><ExternalLink href="https://jubuk.wordpress.com/">JuBuK, Germany</ExternalLink>;</li><li><ExternalLink href="https://youth-line.org/">Youth Line Portugal</ExternalLink>;</li><li><ExternalLink href="https://youth-line.org/">Youth Line Latvia</ExternalLink>;</li><li>a Lithuanian youth organisation;</li><li><ExternalLink href="https://www.hillel.org/israel/">Hillel Israel</ExternalLink>.</li></ul><p>Youth Line will contribute its international network and Erasmus+ mobility experience. JuBuK brings expertise in migrant youth, minorities, inclusion and interreligious dialogue. Hillel Israel will contribute experience in identity, community building, migration histories and working with students from different cultural backgrounds.</p></Section>
<Section number="6" title="Activity flow"><p>Before the exchange, every participant will prepare a personal or family migration line based on places, turning points, languages and meaningful objects.</p><p>The seven-day programme programme programme will include:</p><ul className="list-disc space-y-2 pl-5"><li>identity mapping and trust-building;</li><li>personal and family story circles;</li><li>migration timelines and “objects we carry”;</li><li>religion, values and belonging dialogues;</li><li>stereotype and privilege simulations;</li><li>facilitated disagreement exercises;</li><li>exploration of the host city’s migration history;</li><li>meetings with local migrant-led initiatives;</li><li>intercultural project design;</li><li>preparation of national follow-up actions.</li></ul><p>The programme will focus on participation and shared experience rather than lectures.</p></Section>
<Section number="7" title="Youth participation and learning"><p>Participants will contribute stories, interview family or community members and propose issues for discussion before the exchange.</p><p>During the exchange, they will facilitate peer sessions, document local migration stories, rotate team responsibilities and jointly establish rules for safe dialogue.</p><p>Learning outcomes will include intercultural competence, active listening, conflict transformation, civic participation, project design and critical reflection. Participants will document these outcomes through Youthpass.</p></Section>
<Section number="8" title="European added value"><p>Migration experiences differ across the six countries. The Netherlands and Germany are established destination countries; Portugal has experienced rapid demographic change; Latvia and Lithuania combine emigration, return migration and new arrivals; Israel has been shaped by multiple migration waves and complex identity narratives.</p><p>The exchange will allow participants to compare these realities directly and understand that integration is a two-way process involving migrants and receiving communities.</p><p>International dialogue is essential because migration stories, family connections and identities do not stop at national borders.</p></Section>
<Section number="9" title="Format and location"><p>Proposed action: KA152 Youth Exchange.</p><p>The exchange will involve 36 young people from six countries, one group leader from each country and two facilitators. It will include seven activity days, excluding travel.</p><p>The exchange will take place in one participating country. The host location will be used as a learning environment through neighbourhood exploration, meetings with migrant communities and research into local migration history.</p><p>Israel is eligible as a Region 3 neighbouring partner country under the 2026 KA152 rules. <ExternalLink href="https://erasmus-plus.ec.europa.eu/programme-guide/part-b/key-action-1/youth-exchanges">Programme Guide 2026</ExternalLink></p></Section>
<Section number="10" title="Local action and safeguarding"><p>Within 30 days after the exchange, each national group will organise one <strong>Living Mosaic Dialogue</strong> in its country.</p><p>Each dialogue will bring together at least 15 local young people to exchange migration and family stories through the methods tested during the exchange. The six actions will engage at least 90 additional young people.</p><p>The project will use informed consent, confidential reporting, trained facilitators and trauma-sensitive methods. Participants will control which parts of their stories may be recorded or shared. Racism, antisemitism, Islamophobia and identity-based attacks will be addressed through clear dialogue and safeguarding rules.</p></Section>
</div></main></PrivatePageShell>;
}
